/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fertilizers;

import database.DatabaseConnection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author ProjectTeam
 */
public class PaymentForm extends AbstractForm {

    private ComboBoxModel farmerModel;

    public PaymentForm(JFrame prev) {
        super(prev);
        initComponents();
        initialize();
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
        initialize();
        this.setLocationRelativeTo(null);
    }

    private ComboBoxModel getFarmerModel() {
        FarmerModel[] farmers = null;
        ArrayList<FarmerModel> flist = new ArrayList();

        this.stmt = DatabaseConnection.getConnection().getStatement();

        this.query = "SELECT * FROM v_farmer_account";

        try {
            this.rs = this.stmt.executeQuery(this.query);
            while (this.rs.next()) {
                flist.add(new FarmerModel(this.rs.getLong("Farmer ID"),
                        this.rs.getString("Name"),
                        this.rs.getString("Mobile"),
                        this.rs.getLong("Account No."),
                        this.rs.getDouble("Balance")
                ));
            }

            farmers = new FarmerModel[flist.size()];
            Iterator it = flist.iterator();
            int i = 0;
            while (it.hasNext()) {
                farmers[i++] = (FarmerModel) it.next();
            }

        } catch (SQLException ex) {
            this.jlmsg.setText("Problem getting farmer data");
        }

        this.farmerModel = new DefaultComboBoxModel(farmers);
        return this.farmerModel;
    }

    private void updateBalanceLabel(FarmerModel farmer) {
        this.jlbalance.setText("Rs. " + farmer.getBalance());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbanner = new javax.swing.JLabel();
        jbtback = new javax.swing.JButton();
        jbtlogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlbalancebanner = new javax.swing.JLabel();
        jlbalance = new javax.swing.JLabel();
        jbttrans = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlpaymentsbanner = new javax.swing.JLabel();
        jlfamer = new javax.swing.JLabel();
        jlamount = new javax.swing.JLabel();
        jcbfarmer = new javax.swing.JComboBox<>();
        jbtprocess = new javax.swing.JButton();
        jbtcancel = new javax.swing.JButton();
        jftfamount = new javax.swing.JFormattedTextField();
        jlmsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(675, 620));

        jlbanner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbanner.setText("Payment Entry");

        jbtback.setText("Back");

        jbtlogout.setText("Logout");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbalancebanner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbalancebanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbalancebanner.setText("Current Balance");

        jlbalance.setBackground(new java.awt.Color(204, 255, 255));
        jlbalance.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jlbalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbalance.setText("6000.00");

        jbttrans.setText("Show Transactions");
        jbttrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbalancebanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbttrans, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbalancebanner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jlbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbttrans, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlpaymentsbanner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlpaymentsbanner.setText("Enter Payment");

        jlfamer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlfamer.setText("Famer : ");

        jlamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlamount.setText("Deposit Amount : ");

        jcbfarmer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbfarmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbfarmerActionPerformed(evt);
            }
        });

        jbtprocess.setText("Process");
        jbtprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtprocessActionPerformed(evt);
            }
        });

        jbtcancel.setText("Cancel");
        jbtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcancelActionPerformed(evt);
            }
        });

        jftfamount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlfamer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbfarmer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbtcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtprocess, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jlamount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jftfamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlpaymentsbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpaymentsbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlfamer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbfarmer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlamount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfamount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtprocess)
                    .addComponent(jbtcancel))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtback, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlbanner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlmsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtback, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbfarmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbfarmerActionPerformed
        // TODO add your handling code here:
        this.updateBalanceLabel((FarmerModel) this.jcbfarmer.getSelectedItem());
    }//GEN-LAST:event_jcbfarmerActionPerformed

    private void jbtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcancelActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jbtcancelActionPerformed

    private void jbttransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttransActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        (new TransactionsForm(this, ((FarmerModel) this.jcbfarmer.getSelectedItem()).getAccountId() + "")).setVisible(true);
    }//GEN-LAST:event_jbttransActionPerformed

    private void jbtprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtprocessActionPerformed
        // TODO add your handling code here:
        processPayments();
    }//GEN-LAST:event_jbtprocessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtback;
    private javax.swing.JButton jbtcancel;
    private javax.swing.JButton jbtlogout;
    private javax.swing.JButton jbtprocess;
    private javax.swing.JButton jbttrans;
    private javax.swing.JComboBox<String> jcbfarmer;
    private javax.swing.JFormattedTextField jftfamount;
    private javax.swing.JLabel jlamount;
    private javax.swing.JLabel jlbalance;
    private javax.swing.JLabel jlbalancebanner;
    private javax.swing.JLabel jlbanner;
    private javax.swing.JLabel jlfamer;
    private javax.swing.JLabel jlmsg;
    private javax.swing.JLabel jlpaymentsbanner;
    // End of variables declaration//GEN-END:variables

    private void initialize() {
        this.jcbfarmer.setModel(this.getFarmerModel());
        this.updateBalanceLabel((FarmerModel) this.jcbfarmer.getSelectedItem());
    }

    private void processPayments() {

        String amountEntered;
        double amount = 0;
        double balance;
        FarmerModel farmer;

        //initialization ---->
        this.errors.clear();
        this.success.clear();

        //read data from screen ---->
        farmer = (FarmerModel) this.jcbfarmer.getSelectedItem();
        amountEntered = this.jftfamount.getText();

        //validation ---->
        if (farmer == null) {
            this.errors.add("No farmer account selected");
        }

        try {
            amount = Double.parseDouble(amountEntered);

            if (amount <= 0) {
                this.errors.add("Cannot process zero or negative payments");
            }
        } catch (NumberFormatException ex) {
            this.errors.add("Enter a decimal number in amound field");
        }

        //processing ---->
        if (this.errors.isEmpty()) {

            this.stmt = DatabaseConnection.getConnection().getStatement();

            //get current balance from the farmer model
            balance = farmer.getBalance();

            //calculate new balance
            balance += amount;

            //create transaction entry
            try {
                java.sql.Date today = new java.sql.Date((new java.util.Date()).getTime());

                this.query = "INSERT INTO transaction "
                        + "(accountid, date, type, amount) "
                        + "VALUES "
                        + "('" + farmer.getAccountId() + "', '" + today + "', '" + 0 + "', "
                        + "'" + amount + "')";

                this.stmt.executeUpdate(this.query);
                
                //if successfull, update the databse now with new balance
                this.query = "UPDATE account "
                        + "SET balance=" + balance
                        + " WHERE id=" + farmer.getAccountId();

                this.stmt.executeUpdate(this.query);

                //if updated successfully, update the balance in the combobox's model
                this.updateBalanceToModel(balance);

                //updaet the current balance label on the screen
                this.updateBalanceLabel(farmer);

                this.success.add("Payment processed successfully");
                this.clearFields();

            } catch (SQLException ex) {
                this.errors.add("Problem updating database");
            }
        }

        if (!this.errors.isEmpty()) {
            this.jlmsg.setText(this.msgListToString(this.errors));
        } else if (!this.success.isEmpty()) {
            this.jlmsg.setText(this.msgListToString(this.success));
        }

    }

    private void updateBalanceToModel(double balance) {
        int selFarmer;

        selFarmer = this.jcbfarmer.getSelectedIndex();

        if (selFarmer >= 0) {
            ((FarmerModel) this.farmerModel.getElementAt(selFarmer)).setBalance(balance);
        }
    }

    private void clearFields() {
        this.jcbfarmer.setSelectedIndex(0);
        this.jftfamount.setText("");
    }

}
