/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fertilizers;

import database.DatabaseConnection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author ProjectTeam
 */
public class ProductsForm extends AbstractForm {

    
    public ProductsForm(JFrame prev) {
        super(prev);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * Creates new form ProductsForm
     */
    public ProductsForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlheader = new javax.swing.JLabel();
        jlname = new javax.swing.JLabel();
        jldescription = new javax.swing.JLabel();
        jlcomposition = new javax.swing.JLabel();
        jlstock = new javax.swing.JLabel();
        jtfname = new javax.swing.JTextField();
        jtfcomp = new javax.swing.JTextField();
        jtfstock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtadesc = new javax.swing.JTextArea();
        jbtcreate = new javax.swing.JButton();
        jbtclear = new javax.swing.JButton();
        jbtback = new javax.swing.JButton();
        jlprice = new javax.swing.JLabel();
        jtfprice = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlmsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 620));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlheader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlheader.setText("Add New Fertilizer Products");

        jlname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlname.setText("Name : ");

        jldescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jldescription.setText("Description : ");

        jlcomposition.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlcomposition.setText("Composition : ");

        jlstock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlstock.setText("Initial Stock : ");

        jtadesc.setColumns(20);
        jtadesc.setRows(5);
        jScrollPane1.setViewportView(jtadesc);

        jbtcreate.setText("Create");
        jbtcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcreateActionPerformed(evt);
            }
        });

        jbtclear.setLabel("Clear");
        jbtclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtclearActionPerformed(evt);
            }
        });

        jbtback.setLabel("Back");
        jbtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbackActionPerformed(evt);
            }
        });

        jlprice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlprice.setText("Price : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlheader, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jldescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlcomposition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlprice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfprice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlstock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtback, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtclear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfstock, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlheader, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jldescription, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlprice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfprice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcomposition, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlstock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfstock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtclear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtback, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jlprice.getAccessibleContext().setAccessibleName("jllabel1");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlmsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcreateActionPerformed
        // TODO add your handling code here:
        
        //declaration
        String name = this.jtfname.getText();
        String description = this.jtadesc.getText();
        String composition = this.jtfcomp.getText();
        String stock = this.jtfstock.getText();
        String price = this.jtfprice.getText();
        double dbPrice = 0.00;
        
        //initialize
        this.errors.clear();
        this.success.clear();
        
        //validate screen fields
        if(name == null || name.isEmpty()){
            this.errors.add("Name cannot be empty");
        }
        
        if(description == null || description.isEmpty()){
            this.errors.add("Description cannot be empty");
        }
        
        if(composition == null || composition.isEmpty()){
            this.errors.add("Composition cannot be empty");
        }
        
        if(stock == null || stock.isEmpty()){
            this.errors.add("Initial stock cannot be empty");
        } else {
            try{
                int qty = Integer.parseInt(stock);
                if(qty < 0) {
                    //12.04.2016
                    this.errors.add("Initial stock cannot be negative");
                }
            } catch (NumberFormatException ex){
                this.errors.add("Stock can be only a whole number. Do not enter anything else.");
            }
        }    
        
        if (price == null || price.isEmpty()) {
            this.errors.add("Price cannot be empty");
        } else {
            try {
                dbPrice = Double.parseDouble(price);
                if (dbPrice < 0) {
                    //12.04.2016
                    this.errors.add("Price cannot be negative");
                }
            } catch (NumberFormatException ex) {
                this.errors.add("Please enter a decimal number in price field");
            }
        }
        //create entries database
        if(this.errors.isEmpty()){
            
            this.stmt = DatabaseConnection.getConnection().getStatement();
            
            this.query = "SELECT id "
                    + "FROM products "
                    + "WHERE name='" + name + "' AND description='" + description + "' "
                    + "AND composition='" + composition + "'";
            
            try {
                this.rs = this.stmt.executeQuery(this.query);
                
                if(!this.rs.next()){
                    this.query = "INSERT INTO products "
                            + "(name, description, composition, stockqty) "
                            + "VALUES "
                            + "('" + name + "', '" + description + "', '" + composition + "', "
                            + "'" + stock + "', '" + dbPrice + "')";
                    
                    this.rs = null;
                    
                    Integer numero = this.stmt.executeUpdate(this.query, Statement.RETURN_GENERATED_KEYS);
                    this.rs = this.stmt.getGeneratedKeys();
                    
                    if (this.rs != null && this.rs.next()) {
                        this.success.add("Product with ID " + this.rs.getLong(1) + " is created successfully");
                    }
                    
                } else {
                   this.errors.add("A product with same details already exists"); 
                }
            } catch (SQLException ex) {
                this.errors.add("Database connection failed");
            }
        }
        
        if (!this.errors.isEmpty()) {
            this.jlmsg.setText(this.msgListToString(this.errors));
        }

        if (!this.success.isEmpty()) {
            this.jlmsg.setText(this.msgListToString(this.success));
        }
    }//GEN-LAST:event_jbtcreateActionPerformed

    private void jbtclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtclearActionPerformed
        // TODO add your handling code here:
        this.clearFormFields();
    }//GEN-LAST:event_jbtclearActionPerformed

    private void jbtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbackActionPerformed
        // TODO add your handling code here:
        this.goToPrevious();
    }//GEN-LAST:event_jbtbackActionPerformed

    private void clearFormFields(){
        this.jtadesc.setText("");
        this.jtfcomp.setText("");
        this.jtfname.setText("");
        this.jtfstock.setText("");
        this.jtfprice.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtback;
    private javax.swing.JButton jbtclear;
    private javax.swing.JButton jbtcreate;
    private javax.swing.JLabel jlcomposition;
    private javax.swing.JLabel jldescription;
    private javax.swing.JLabel jlheader;
    private javax.swing.JLabel jlmsg;
    private javax.swing.JLabel jlname;
    private javax.swing.JLabel jlprice;
    private javax.swing.JLabel jlstock;
    private javax.swing.JTextArea jtadesc;
    private javax.swing.JTextField jtfcomp;
    private javax.swing.JTextField jtfname;
    private javax.swing.JTextField jtfprice;
    private javax.swing.JTextField jtfstock;
    // End of variables declaration//GEN-END:variables
}
