/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fertilizers;

import database.DatabaseConnection;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author ProjectTeam
 */
public class PurchaseReport extends AbstractForm {

    private ALVTableModel alvModel;
    
    public PurchaseReport(JFrame prev){
        super(prev);
        initComponents();
        initialize();
        this.setLocationRelativeTo(null);
    }
    /**
     * Creates new form SalesReport
     */
    public PurchaseReport() {
        initComponents();
        initialize();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbanner = new javax.swing.JLabel();
        jlmsg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbsalesreport = new javax.swing.JTable();
        jbtback = new javax.swing.JButton();
        jbtlogout = new javax.swing.JButton();
        jbtprintinv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbanner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbanner.setText("Purchase Report");

        jtbsalesreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbsalesreport);

        jbtback.setText("Back");
        jbtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbackActionPerformed(evt);
            }
        });

        jbtlogout.setText("Logout");
        jbtlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlogoutActionPerformed(evt);
            }
        });

        jbtprintinv.setText("Print Invoices");
        jbtprintinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtprintinvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jlmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 232, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtback, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtprintinv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbanner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtback, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtprintinv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbackActionPerformed
        // TODO add your handling code here:
        this.goToPrevious();
    }//GEN-LAST:event_jbtbackActionPerformed

    private void jbtlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        (new LoginForm()).setVisible(true);
    }//GEN-LAST:event_jbtlogoutActionPerformed

    private void jbtprintinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtprintinvActionPerformed
        // TODO add your handling code here:
        this.printInvoices();
    }//GEN-LAST:event_jbtprintinvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtback;
    private javax.swing.JButton jbtlogout;
    private javax.swing.JButton jbtprintinv;
    private javax.swing.JLabel jlbanner;
    private javax.swing.JLabel jlmsg;
    private javax.swing.JTable jtbsalesreport;
    // End of variables declaration//GEN-END:variables

    private void initialize() {
        
        this.stmt = DatabaseConnection.getConnection().getStatement();

        this.query = "SELECT * "
                + "FROM v_purchase_report ";

        try {
            this.rs = this.stmt.executeQuery(this.query);
            this.alvModel = new ALVTableModel(this.rs);

            this.jtbsalesreport.setModel(alvModel);

            if (this.rs.getMetaData().getColumnCount() <= 0) {
                this.jlmsg.setText("No purchase entry made yet");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FarmerAccountsForm.class.getName()).log(Level.SEVERE, null, ex);
            this.jlmsg.setText("Some problem fetching the purchase report. Try after some time!!");
        }
    }
    
    private void printInvoices() {
        int[] selIndex;
        Set<Long> orderIds;

        orderIds = new HashSet();

        if (this.alvModel != null) {
            selIndex = this.jtbsalesreport.getSelectedRows();

            if (selIndex.length < 1) {
                this.jlmsg.setText("Select at least one row to print invoices");
                return;
            }

            //get the index of the column "Order No."
            String[] columnNames = this.alvModel.getColumns();
            int colInd = -1;
            for (int i = 0; i < columnNames.length; i++) {
                if (columnNames[i].equalsIgnoreCase("Order No.")) {
                    colInd = i;
                    break;
                }
            }

            if (colInd < 0) {
                this.jlmsg.setText("Selected Row does not have order number");
                return;
            }

            //get the value of Order Numbers for each selected row - but do not have duplicates
            for (int index : selIndex) {
                orderIds.add(Long.parseLong((String) this.alvModel.getValueAt(index, colInd)));
            }

            Iterator oi = orderIds.iterator();
            while (oi.hasNext()) {
                long orderId = (Long) oi.next();
                PurchaseInvoicePdf pi = new PurchaseInvoicePdf(orderId);
                try {
                    String filecreatedat = pi.createPdf();
                    this.success.add("Invoice saved at : " + filecreatedat);
                } catch (Exception ex) {
//                    this.jlmsg.setText(ex.getMessage());
                    this.errors.add(ex.getMessage());
                }
            }

            if (!this.success.isEmpty()) {
                this.jlmsg.setText(this.msgListToString(this.success));
            }

            if (!this.errors.isEmpty()) {
                this.jlmsg.setText(this.msgListToString(this.errors));
            }
        } else {
            this.jlmsg.setText("No orders exist to print invoices");
        }

    }
}
