/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fertilizers;

import database.DatabaseConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ProjectTeam
 */
public class TestALVTableSimpleClassModel extends javax.swing.JFrame {

    /**
     * Creates new form TestALVTableSimpleClassModel
     */
    public TestALVTableSimpleClassModel() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Remove Row");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int[] rows = this.jTable1.getSelectedRows();
        ((ALVTableSimpleClassModel)this.jTable1.getModel()).removeSelectedRows(rows);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestALVTableSimpleClassModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestALVTableSimpleClassModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestALVTableSimpleClassModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestALVTableSimpleClassModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestALVTableSimpleClassModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void initializeDynamicTable(){
        
        Statement stmt;
        ResultSet rs;
        String query;

        Vector<Object[]> data = new Vector();
        Object[]  row;
        
        String[] headers = null;
        int columnCount = 0;
        int colIndex;

        query = "SELECT * FROM products";
        stmt = DatabaseConnection.getConnection().getStatement();
        
        try {
            rs = stmt.executeQuery(query);
            columnCount = rs.getMetaData().getColumnCount();
            headers = new String[columnCount];
            
            for (int i = 0; i < columnCount; i++) {
                headers[i] = rs.getMetaData().getColumnName(i + 1);
            }
            
            while(rs.next()){
                row = new Object[columnCount];
                for(colIndex = 0; colIndex < columnCount; colIndex++){
                    row[colIndex] = rs.getString(colIndex + 1);
                }
                data.addElement(row);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TestALVTableSimpleClassModel.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.jTable1.setModel(new ALVDynamicTableModel(data, headers));
    }
    
    
    private void initialize() {
        Statement stmt;
        ResultSet rs;
        String query;
        
        Object[][] data = null;
        String[] headers = null;
        int columnCount = 0, rowCount = 0;
        int rowIndex, colIndex;
        
        ArrayList<Object[]> dataSet = new ArrayList();
        
        query = "SELECT * FROM products";
        
        stmt = DatabaseConnection.getConnection().getStatement();
        
        try {
            rs = stmt.executeQuery(query);
            
            columnCount = rs.getMetaData().getColumnCount();
            headers = new String[columnCount];
            
            for(int i = 0; i < columnCount; i++) {
                headers[i] = rs.getMetaData().getColumnName(i+1);
            }
            
            rowIndex = 0;
            while(rs.next()){
                Object[] row = new Object[columnCount];
                for(colIndex = 1; colIndex <= columnCount ; colIndex++){
                    row[colIndex - 1] = rs.getString(colIndex); //colIndex in result set starts from 1 and NOT zero
                }               
               dataSet.add(row);
            }
            
            rowCount = dataSet.size();
            if(!dataSet.isEmpty()){
                data = new Object[rowCount][columnCount];
                for(rowIndex = 0; rowIndex < rowCount; rowIndex++) {
                    for(colIndex = 0; colIndex < columnCount; colIndex++){
                        data[rowIndex][colIndex] = ((Object[])dataSet.get(rowIndex))[colIndex];
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(TestALVTableSimpleClassModel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.jTable1.setModel(new ALVTableSimpleClassModel(data, headers));
    }
}
